plot(1:length(fidelList{1}),fidelList{1}.','b',...
     1:length(fidelList{2}),fidelList{2}.','r',...
     1:length(fidelList{3}),fidelList{3}.','g',...
     1:length(fidelList{4}),fidelList{4}.','m');